# Generated by Django 4.0.6 on 2022-07-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_familia_delete_curso_delete_entregable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Papa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='familia',
        ),
    ]
